### ISSUE TITLE
FEATURE update to HAProxy 2.0 or 2.1

### ISSUE THREAD

**Issue by git001** [jiangwenyuan/nuster#56]
**Is this a BUG report or FEATURE request?**: FEATURE 

Do you plan to update to HAProxy 2.0 or 2.1?

**Comment by jiangwenyuan** [comment]
Yes, working on migrating to 2.0 now

**Comment by git001** [comment]
cool do you need help or support?

**Comment by jiangwenyuan** [comment]
Yes, that would be great help:)

**Comment by git001** [comment]
how can I help?

Maybe we should directly switch to 2.1 because it have also fcgi mux and therefore it makes it possible to use nuster in front of php-fpm and other fcgi servers.

It looks like that 2.1 will be released soon https://www.mail-archive.com/haproxy@formilux.org/msg35469.html

What do you think about this suggestion?
You use `nbproc 12` in the benchmarks https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-performance-benchmark:-nuster-vs-nginx-vs-varnish-vs-squid is nuster thread safe because `nbproc` is depricated and will be removed in the future of haproxy.

**Comment by jiangwenyuan** [comment]
I think we should migrate to 2.0 first because it's LTS version while 2.1 is a development release and it's easier to migrate as it seems 2.1 has completely moved to HTX which causes much more work to migrate.

> nbproc is depricated and will be removed in the future of haproxy

I don't know that, nbthread should also work

Here's some todo list after migration to 2.0

* Vary support
* Range support
* Last-Modified/If-Modified-Since/If-Unmodified-Since/ETag/If-None-Match/If-Match support(#15 )
* Auto extend TTL(#29 )
* Other github issues

After that I'm thinking to migrate to 2.1 and add support for node replication, which I completely have no idea right now.

**Comment by git001** [comment]
> I think we should migrate to 2.0 first because it's LTS version

Perfect. Where can I help you.

**Comment by jiangwenyuan** [comment]
The migration itself wouldn't be necessary as I've already been working on it. How about the todo list? 
Or maybe the node replication:)

**Comment by git001** [comment]
Well due to fact that I'm not a good programmer I would like to offer you some help for test and documentation.  
When ever you think that there is a version which is usable with 2.0 I would like to test it.

**Comment by jiangwenyuan** [comment]
Of course, thank you so much for the help for test and documentation, that would be great help. I always wanted to enrich the documentation, add more context, manuals, etc.

**Comment by git001** [comment]
Okay do you want to keep this issue open until the update to 2.0 is done or do you prefer to close it?  
I'm fine either way.

**Comment by jiangwenyuan** [comment]
Let me close it, any PR is welcome:)
